name: Order Notification

on:
  repository_dispatch:
    types: [new-order]

jobs:
  send-telegram-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Send order to Telegram
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendMessage" \
          -d chat_id="$TELEGRAM_CHAT_ID" \
          -d text="${{ github.event.client_payload.message }}" \
          -d parse_mode="Markdown"
